### ISSUE TITLE
do I have to upgrade cocoa pods to version 1.4.0+ to compile swift 4?

### ISSUE THREAD

**Issue by romk1n** [Raizlabs/BonMot#311]
Trying to compile using cocoa pods 1.3.1 and getting many errors for swift4 like this 

```
Pods/BonMot/Sources/UIKit/AdaptableTextContainer.swift:44:38: error: cannot assign value of type 'BONFont?' (aka 'Optional<UIFont>') to type 'UIFont!'
            font = attributes[.font] as? BONFont
```

smells like I am doing something wrong, but the version of BonMot is 5.0

**Comment by romk1n** [comment]
my fault didn't do `pod install` after `pod update`

**Comment by ZevEisenberg** [comment]
Huh, you shouldn't have to `pod install` after `pod update`, but I'm glad it's working for you now!
